[window]
dynamic_padding = true
padding = { x = 5, y = 5 }
startup_mode = "Maximized"
decorations = "buttonless"
opacity = 0.95

[scrolling]
history = 100000

[font]
normal = { family = "MesloLGMDZ Nerd Font Mono", style = "Regular" }
size = 15
offset = { x = 1, y = 4 }
glyph_offset = { x = 1, y = 2 }

[selection]
save_to_clipboard = true

[mouse]
bindings = [{ mouse = "Right", mods = "Control", action = "Paste" }]

[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]
