[window]
dynamic_padding = true
# option_as_alt = "Both"
padding = { x = 5, y = 5 }
startup_mode = "Maximized"
decorations = "buttonless"

[scrolling]
history = 100000

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 15
offset = { x = 1, y = 4 }
glyph_offset = { x = 1, y = 2 }

[selection]
save_to_clipboard = true

[mouse]
bindings = [{ mouse = "Right", mods = "Control", action = "Paste" }]

# Colors (Tokyo Night)
# Source https//github.com/zatchheems/tokyo-night-alacritty-theme

# Default colors
[colors.primary]
background = '#1a1b26'
foreground = '#a9b1d6'

# Normal colors
[colors.normal]
black   = '#32344a'
red     = '#f7768e'
green   = '#9ece6a'
yellow  = '#e0af68'
blue    = '#7aa2f7'
magenta = '#ad8ee6'
cyan    = '#449dab'
white   = '#787c99'

# Bright colors
[colors.bright]
black   = '#444b6a'
red     = '#ff7a93'
green   = '#b9f27c'
yellow  = '#ff9e64'
blue    = '#7da6ff'
magenta = '#bb9af7'
cyan    = '#0db9d7'
white   = '#acb0d0'
