[tools]
elixir = "1.18.0-otp-27"
erlang = "27.2.3"
go = "1.23.2"
node = "latest"
postgres = "17.5"
python = "3.12.3"
ruby = "4.0.1"
rust = "1.90.0"
terraform = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]
