[tools]
elixir = "1.18.0-otp-27"
erlang = "27.2.3"
go = "1.25.0"
node = "latest"
pnpm = "11.1.2"
postgres = "17.5"
python = "3.12.3"
ruby = "3.4.7"
rust = "1.90.0"
terraform = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]
