[tools]
elixir = "1.18.0-otp-27"
erlang = "27.2.3"
go = "1.22.2"
node = "22.14.0"
python = "3.12.3"
ruby = "3.2.6"
rust = "1.79.0"
terraform = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]
