return {
  "folke/snacks.nvim",
  priority = 1000,
  lazy = false,
  opts = {
    bigfile = { enabled = true },
    bufdelete = { enabled = true },
    dashboard = { enabled = true },
    debug = { enabled = false },
    git = { enabled = false },
    gitbrowser = { enabled = true },
    lazygit = { enabled = true },
    notify = { enabled = true },
    notifier = { enabled = true, timeout = 3000 },
    profiler = { enabled = false },
    quickfile = { enabled = true },
    rename = { enabled = false },
    scratch = { enabled = false },
    statuscolumn = { enabled = false },
    terminal = { enabled = true },
    toggle = { enabled = true },
    win = { enabled = false },
    words = { enabled = false },
  },
  keys = {
    { "Q", function() Snacks.bufdelete() end, desc = "Delete Buffer" },
    { "<leader>gB", function() Snacks.gitbrowse() end, desc = "Git Browse" },
    { "<leader>gf", function() Snacks.lazygit.log_file() end, desc = "Lazygit Current File History" },
    { "<leader>gg", function() Snacks.lazygit() end, desc = "Lazygit" },
    { "<leader>gl", function() Snacks.lazygit.log() end, desc = "Lazygit Log (cwd)" },
    { "<leader>un", function() Snacks.notifier.hide() end, desc = "Dismiss All Notifications" },
    { "<c-\\>",     function() Snacks.terminal() end, desc = "Toggle Terminal" },
  },
}
